name: duodo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  auto_route: ^8.1.3
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.3
  get_it: ^7.7.0
  flutter_bloc: ^9.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_displaymode: ^0.6.0
  logger: ^2.3.0
  async: ^2.11.0
  path: ^1.9.0
  path_provider: ^2.1.3
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_iconpicker: ^4.0.1
  drift_flutter: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  drift_dev: ^2.18.0
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  fonts:
    - family: Rosario
      fonts:
        - asset: assets/fonts/Rosario-Italic.ttf
          style: italic
        - asset: assets/fonts/Rosario-Light.ttf
          weight: 300
        - asset: assets/fonts/Rosario-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rosario-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rosario-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rosario-Bold.ttf
          weight: 700
