// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNTVK9eaX8Zx2wfLylgX9g8ODHnuICEs',
    appId: '1:370900009440:android:af74f581597670782bab85',
    messagingSenderId: '370900009440',
    projectId: 'duodo-fe15e',
    storageBucket: 'duodo-fe15e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHSHla8tPHwc_uhNsVS00cqLEOELipb28',
    appId: '1:370900009440:ios:5f81630e18c15b352bab85',
    messagingSenderId: '370900009440',
    projectId: 'duodo-fe15e',
    storageBucket: 'duodo-fe15e.firebasestorage.app',
    androidClientId: '370900009440-3qi24oe1k3mcmppr094lecavms3i44jf.apps.googleusercontent.com',
    iosClientId: '370900009440-83or1cisvleep4sndue3flo9r35n4s0l.apps.googleusercontent.com',
    iosBundleId: 'com.fundatomic.duodo.duodo',
  );
}
